name: Publish

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag_name'
        required: true
        type: string
      registry:
        description: 'bazel central registry target'
        required: false
        default: 'fweikert/bazel-central-registry'
        type: string
      registry-fork:
        description: ''
        required: true
        default: publish-to-bcr-dev/bazel-central-registry
        type: string

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  publish:
    uses: publish-to-bcr-dev/.github/.github/workflows/publish.yaml@v10.0.0
    with:
      tag_name: ${{ inputs.tag_name }}
      registry: ${{ inputs.registry }}
      registry_fork: ${{ inputs.registry-fork }}
    secrets:
      publish_token: ${{ secrets.PUBLISH_TOKEN }}